name: Build and Deploy to Staging
on:
  push:
    branches:
      - deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Step 3: Build the JAR
      - name : Installing local dependency
        run : |
              mvn install:install-file -Dfile=libs/motech-pax-it-0.27.8.jar -DgroupId=org.motechproject -DartifactId=motech-pax-it -Dversion=0.27.8 -Dpackaging=jar
              mvn install:install-file -Dfile=libs/motech-scheduler-0.27.8.jar -DgroupId=org.motechproject -DartifactId=motech-scheduler -Dversion=0.27.8 -Dpackaging=jar
              mvn clean install

      # Step 4: Store deployment data
      - uses: actions/upload-artifact@v4
        with:
          name: nms-jars
          path: |
            csv/target/*.jar
            kilkari/target/*.jar


